nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #allow_credentials: true #Only when security cookies are used
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: [
            'Content-Type', 'Authorization', 'Accept', 'Fields',
            'Preload', 'Prefer', 'Cache-Control', 'X-Requested-With',
            'If-Match', 'If-None-Match' # For ETag support
        ]
        expose_headers: [
            'Link', 'X-Total-Count', 'ETag', 'Location',
            'Content-Location', 'Content-Range'
        ]
        max_age: 86400
        forced_allow_origin_value: ~

    paths:
        '^/': ~
